### PR TITLE
Updated version number in documentation to match released version

### PR DESCRIPTION
**Pull request by robert-lindstrom**
#### Category
- [ ] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [X] Documentation update?

#### What's in this Pull Request?

Updated mkdocs.yml with version number matching the latest released version. [https://pnp.github.io/pnpjs/](https://pnp.github.io/pnpjs/) and locally generated documentation was showing version 1.2.3 when the current version is 1.2.7.

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks - obviously need to automate that since I've not been remembering to update it.

**Comment by simonagren** [comment]
@patrick-rodgers shouldnt it be 1.2.8 then, if it will be in the next release? 😀

**Comment by patrick-rodgers** [comment]
Well it should be then, but not yet. As I mentioned I think it needs to be automated since relying on me to remember stuff obviously isn't working.

**Comment by simonagren** [comment]
Yeah ok, sounds good!

**Pull request merged**
