### PR TITLE
Commiting with some tests

### PR DESCRIPTION
**Pull request by ValerasNarbutas**
#### Category
- [ ] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [x] Documentation update?

#### Related Issues

related to issue #666 

#### What's in this Pull Request?

Added some unit tests for site-users module

*Any comments are welcome*

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Hi @ValerasNarbutas - thanks for this. You've changed 67 files so I am not clear on what work you meant to submit and what work might have accidentally made it into the PR. Can you take a few minutes to clean it up to help with the review? Then we can get things merged. Thanks!

**Comment by ValerasNarbutas** [comment]
Hey, @patrick-rodgers this was accident, 
i will fix it.

**Comment by ValerasNarbutas** [comment]
I will make new one @patrick-rodgers , could not figure it out why so many changes..

**Comment by patrick-rodgers** [comment]
Ok, sounds good. Please get all the latest changes as well, that might help. Not sure when you forked the code but lots of things have been updated recently. Thanks!

**Comment by ValerasNarbutas** [comment]
thanks @patrick-rodgers , indeed, a lot changed.. 
created new pull request #883 . 
Is code coverage report still exist in newer code? npm test with "it.only" runs tests but i am missing whole code coverage report.
Thanks

**Comment by patrick-rodgers** [comment]
I took it out for now so it doesn't run. It made things much slower and with all the uncovered code as we work it wasn't particularly valuable yet. Once we think we are mostly done with v2 beta we can turn it back on and see how it looks.

**Pull request closed without merging**
