### PR TITLE
[2.0.0] sub module: SP-views #673

### PR DESCRIPTION
**Pull request by nanddeepn**
#### Category
- [x] Bug fix?
- [x] Documentation update?

#### Related Issues
fixes https://github.com/pnp/pnpjs/issues/673

#### What's in this Pull Request?
Dev-v2 changes for View
- Minor changes to Types
- Added test cases
- Updated documentation

#### Guidance
Dev-v2 changes for View
- Minor changes to Types
- Added test cases
- Updated documentation

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks, am catching up on merging, will work on getting this one in tomorrow or Wed.

**Comment by nanddeepn** [comment]
Thanks @patrick-rodgers 
The changes are done before our call last Friday. In case, I have missed any thing please let me know.
Thank you.

**Comment by patrick-rodgers** [comment]
Thanks @nanddeepn ! I made a few changes and updated the tests. Appreciate your help on this!

**Comment by nanddeepn** [comment]
Thank you @patrick-rodgers

**Pull request merged**
