### PR TITLE
update nodejs sample app and docs to [v3]

### PR DESCRIPTION
**Pull request by aaademosu**
#### Category
- [ ] Bug fix?
- [ ] New feature?
- [x] Documentation update?
- [x] Updated sample?

## Updated docs
- docs/authentication/server-nodejs.md: *Removed the sections about using SharePoint app registration and ADAL section as authentication is now only available via MSAL for nodejs*
- docs/getting-started.md: *Updated to showcase usage of the v3 libraries for nodejs*

## Sample Nodejs App
- Updated to use esm libs to showcase usage of SharePoint and Microsoft Graph APIs.

### CODE REVIEW

**Comment by aaademosu** [comment]
Hi @patrick-rodgers, updated the nodejs sample and some of the docs for nodejs usage. 

Working my way through the tests and samples. Would share any additional feedback as i test.

**Comment by juliemturner** [comment]
This is awesome!!! Thank you so much for helping us out with these samples.  Just wanted to validate that you meant to certs path (samples/nodejs-app/certs/cert.pem)? If so, all good, just didn't know if they were for real and you just didn't realize then ended up in the PR.

**Comment by aaademosu** [comment]
Yes i did, since they are self signed. It would make running that sample easier.

**Comment by patrick-rodgers** [comment]
This is great stuff, thank you! I'd like to please back out the certs from the PR. I understand the idea of wanting the sample to be easier to run, but we can't encourage folks to install certs into their tenants to which the private keys are public.

Really appreciate you jumping in and making these updates, will be a huge help in getting v3 ready for release!

**Comment by aaademosu** [comment]
Sure. No worries. Would update the PR.

**Comment by aaademosu** [comment]
Certificates have been removed and docs updated as well

**Comment by patrick-rodgers** [comment]
Thank you @aaademosu for this contribution!

**Pull request merged**
