### PR TITLE
Feature/v2 users

### LINKED ISSUE #657: [2.0.0] sub module: GRAPH-users
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

### PR DESCRIPTION
**Pull request by baywet**
#### Category
- [ ] Bug fix?
- [x] New feature?
- [ ] New sample?
- [x] Documentation update?

#### Related Issues

fixes #657 

#### What's in this Pull Request?
- adds unit tests for v2 pnp graph users
- adds documentation for v2 pnp graph users

Note: this is my first attempt contributing to v2, I probably missed a few things. Don't hesitate to let me know how I can correct course :)

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks! Appreicate you helping get us closer to v2!

**Comment by baywet** [comment]
Thanks @patrick-rodgers !! So I didn't miss anything? Should I take another one?

**Comment by patrick-rodgers** [comment]
I made a few small updates like I always do - was good. Please, yes, if you have time would be great!

**Comment by PopWarner** [comment]
@baywet, lemme know if you’d decide you want one and I’ll get it labeled for ya! Thanks again man, you rock! :)

**Pull request merged**
