### PR TITLE
fix dead promise & handle token provider exception

### PR DESCRIPTION
**Pull request by KEMiCZA**
#### Category
- [x] Bug fix?

#### Related Issues
#914

#### What's in this Pull Request?

Fixes a dead promise in the adal getToken method as mentioned in #914

### CODE REVIEW

**Comment by koltyakov** [comment]
Just wondering what is the difference?
The code after the change in regards to promises flow is just the same and equivalent of the previous implementation, but without async/await. The resulted code in both cases will behave the same, yet we considered to prefer async/await syntax.

**Comment by KEMiCZA** [comment]
My bad, I thought since we are returning .then, and we don't catch the exception, that the exception in the getTokenProvider method would not be handled?
```typescript
 return this.context.aadTokenProviderFactory.getTokenProvider().then()...
```
Somehow for me it seems more clean if using the await for this call, since it would throw an exception. But if there's no difference, then I'm mistaken and also confused why the exception is not thrown as @TazzyMan explained.

**Comment by koltyakov** [comment]
With async/await if `getTokenProvider` fails the whole method rejects the Promise, so there is no need in wrapping with try/catch for example. Maybe `getToken` "hangs" somewhere not being caught for example?

**Comment by KEMiCZA** [comment]
Yeah you're right about the async/await and then/this doing the same thing, same as Patrick said. By bad. Was a little confused. Going to close this PR.

**Comment by koltyakov** [comment]
No problem and thank you for assistance, as always a lot appreciated!

**Pull request closed without merging**
