### PR TITLE
implemented getFileById and getFolderById

### LINKED ISSUE #560: Add web.getFileById and web.getFolderById
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Please add `getFileById` and `getFolderById` to `Web`.

Endpoints: 
`/_api/web/GetFileById('1c352119-ef7c-430f-b229-436c82c83783')`
`/_api/web/GetFolderById('1c352119-ef7c-430f-b229-436c82c83783')`

Thank you.

### PR DESCRIPTION
**Pull request by tavikukko**
#### Category
- [ ] Bug fix?
- [x] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

fixes #560 

#### What's in this Pull Request?

implemented methods **getFileById** for endpoint **/_api/web/GetFileById** and **getFolderById** for endpoint **/_api/web/GetFolderById**

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks!

**Comment by wmertens** [comment]
This call is only supported in SharePoint Online.

Would it be a good idea to figure out the SharePoint version somehow and throw errors for all calls that are not supported?

**Comment by tavikukko** [comment]
Oops, my bad, sorry about that. @patrick-rodgers how do we handle these?

**Comment by patrick-rodgers** [comment]
We target SPO primarily, so if something only works there we note that in the code comments and move on. Producing errors or having multiple versions of the library isn't something that we will ever do. I see no value in introducing that complexity into the library.

Look at it this way, if we were only allowed to have methods supported by all versions of the API then we would be stuck with 2013 rest api surface.

**Comment by wmertens** [comment]
Well, it's more that it's not easy to discover if the targeted SP supports the call done. The error messages are not straightforward.

So it would be nice if each problematic call had a check. Limiting the methods to 2013 is of course not nice.

**Pull request merged**
