### PR TITLE
V2 changes for site-groups module

### LINKED ISSUE #664: [2.0.0] sub module: SP-site-groups
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

### PR DESCRIPTION
**Pull request by RamPrasadMeenavalli**
#### Category
- [x] Bug fix?
- [x] New sample?
- [x] Documentation update?

#### Related Issues

fixes #664 ,

#### What's in this Pull Request?
- [x] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [x] Ensure every property/method has at least one test
- [x] Ensure all of the interface method/properties are commented
- [x] Remove comments from class implementation files
- [x] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [x] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [x] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

### CODE REVIEW

**Comment by RamPrasadMeenavalli** [comment]
Additionally I have made the following changes
1. Removed the following interface at line 126 (in packages/sp/src/site-groups/types.ts)
```TypeScript
export interface SiteGroupAddResult {
    group: ISiteGroup;
    data: any;
}
```
Looks like this interface is not used anywhere

2. Added 'import ../security' in packages/sp/src/site-groups/web.ts
Because breakRoleInheritance method is called which is defined in ../security module.

**Comment by patrick-rodgers** [comment]
Hi @RamPrasadMeenavalli - thanks for this PR. Looks like there are a few issues as the CI build failed. Can you please take a look at resolve them? Then we can take a look at getting this merged. Thanks!

**Comment by RamPrasadMeenavalli** [comment]
Hi @patrick-rodgers - Yes, I saw that the CI build has failed. But, when I build it locally, it was successful.
Any suggestions or pointers, where I should start with to fix the CI build issue?

**Comment by patrick-rodgers** [comment]
I re-ran the tests and I get this error:

```
/home/travis/build/pnp/pnpjs/node_modules/ts-node/src/index.ts:240
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/sp/src/security/funcs.ts:59:17 - error TS2339: Property 'hasPermissions' does not exist on type 'SecurableQueryable'.
  Property 'hasPermissions' does not exist on type '_List'.
59     return this.hasPermissions(perms, permission);
                   ~~~~~~~~~~~~~~
packages/sp/src/security/funcs.ts:70:17 - error TS2339: Property 'hasPermissions' does not exist on type 'SecurableQueryable'.
  Property 'hasPermissions' does not exist on type '_List'.
70     return this.hasPermissions(perms, permission);
```

I can have a look but I think you are missing an import.

**Comment by patrick-rodgers** [comment]
I fixed this and merged. The issue was a problem with the typing in the security sub-module. If you included just security/web (which should be fine) it was breaking due to the way a compound type was constructed. I fixed that problem and was able to successfully test and merge.

**I am curious how you were able to run the tests you wrote without fixing that error?**

**Comment by RamPrasadMeenavalli** [comment]
Thank you Patrick.
Now I remember that I commented those 2 calls for hasPermissions whole running the tests. Which I now realize is not the correct way of doing it.

Thank you for the quick help. Good learning for me :)

**Pull request merged**
