### PR TITLE
fix docs

### PR DESCRIPTION
**Pull request by MarkusLanger**
#### Category
- [ ] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [x] Documentation update?

#### What's in this Pull Request?

Fix some documentation.

### CODE REVIEW

**Comment by juliemturner** [comment]
Thanks @MarkusLanger -- Looks like somehow, we got a merge header left in the file. Unfortunately, your PR changed a few other things we don't want to change, like the indents.  If you'd like to make the changes to remove that file from your PR I'll merge this otherwise no problem I'll take care of it during our next release.

**Comment by MarkusLanger** [comment]
Hi @juliemturner ,

Correcting the indentation fixes a problem with the display.

image

**Comment by juliemturner** [comment]
@MarkusLanger -- I'm not seeing any changes in the "Files Changed" tab for the getting-started.md file except the indentations... I can reject just that piece of it, but that's what I'm referring to.

image

**Comment by nisancigokmen** [comment]
...Fix some documentation.

**Comment by MarkusLanger** [comment]
Reset changes in getting-started.md

**Comment by juliemturner** [comment]
Awesome, that's looks great.  Again, thank you for the fix!

**Pull request merged**
