### PR TITLE
renderListData, renderListFormData: OData verbose mode issue fix

### PR DESCRIPTION
**Pull request by koltyakov**
#### Category

- [x] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### What's in this Pull Request?

Fixed renderListData, renderListFormData methods result parsing in verbose OData mode.

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
So we were just looking for the wrong property name? That's odd, I wonder if it changed or if we had it wrong all this time

**Comment by koltyakov** [comment]
Property names were correct, yet the order to parse a result as a JSON wasn't.
With OData=verbose, the response object has the following shape:

```json
{
  "RenderListData": "[JSONified string]"
}
```

JSON.parse was applied to the object but not a property.
On some stage, JSON.parse was moved before hOP condition.

**Comment by patrick-rodgers** [comment]
It looks like this change broke a test, can you have  look? https://travis-ci.com/pnp/pnpjs/builds/85482936

**Comment by koltyakov** [comment]
Oh, my fault, I missed that the property name was incorrect. Pushed a quick fix.

image

**Pull request merged**
