### PR TITLE
minor change  to delete test subsites

### PR DESCRIPTION
**Pull request by ValerasNarbutas**
#### Category
- [x] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [x] Documentation update?

Undocumented function for deletion sub-sites and changed position were function can be called as it would fail if called before spTestSetup.
Subsite deletion was very useful for me personally

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Just merged #888 if you want to double check your changes against that.

**Comment by ValerasNarbutas** [comment]
oh cool, i will check it :)

**Comment by ValerasNarbutas** [comment]
Looks like it did not impact my example file nor amendments to the test file.

**Comment by ValerasNarbutas** [comment]
tsconfig has new line in my changes, tried to remove it does still exist. not sure why.

**Comment by ValerasNarbutas** [comment]
@patrick-rodgers , i noticed links in docs example were changed, updated it in my site-users.md also. should be ok to merge. i will double check after merge if all examples documented also working from newest version.

**Comment by ValerasNarbutas** [comment]
@patrick-rodgers  Messed up again :(, tried to rebase from your commit... 
Please ignore this pull request, i will close it an replicate files into the new version.
Apologize for your time.

**Comment by ValerasNarbutas** [comment]
@patrick-rodgers  i have split this pull request into two separate ones. One for small amendment  in test/main.ts file and one for #666 documentation samples.

**Pull request closed without merging**
