### PR TITLE
Implementation of folder's moveTo method

### PR DESCRIPTION
**Pull request by koltyakov**
#### Category

- [ ] Bug fix?
- [x] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

mentioned in #68

#### What's in this Pull Request?

The PR adds an experimental `moveTo` method for the `Folder` object. The method uses `/_api/SP.MoveCopyUtil.MoveFolder()` API endpoint and allows moving folders within the folders tree.
In comparison to the existing possibility of moving a folder by updating `FileLeafRef` prop, the method allows moving folders on the hight level or a sibling levels (not in the same root folder). Updating FileLeafRef moves folder to the descendant levels and renaming the folder.

@patrick-rodgers, in the implementation I can see some points where I need your opinion on:

- Helper method doesn't mirror API Reference strictly, yet:
  - Being a member method of a Folder might be logical for the library users. We got a folder, then we have the option to move.
  - I'm not very happy with implementing separate `SP.MoveCopyUtil` endpoints for some reasons (redundancy, lack of verbosity, etc.). 
- I didn't find another method as applying `SPHttpClient`, which I know can be probably awkward using inside such methods, also there is some mess with getting urls. Would love hearing about alternatives from you. I would use a new queriable object (or clone and postCore, yet didn't figure out how to deal with custom endpoint here), but can't see a necessity of creating a class for `SP.MoveCopyUtil` at this point.

Please consider the changes from this PR as experimental. I would love to follow the recommendation and applying changes if needed. Also, I'm ok if we will decide to close this PR without merging in case if the implementation looks awkward, etc. :)

### CODE REVIEW

**Comment by wmertens** [comment]
We noticed that if there is an error with the from or to paths, the API will still return 200. Is there some header or so that will let the API return an error when source or destination are missing?

**Comment by koltyakov** [comment]
Thanks @wmertens! I have a feeling it's `MoveFolder`'s behavior, I initially tested with `MoveFolderByPath` it was returning the errors I'm sure as I was getting a bunch of them in a progress. Then I switched to `MoveFolder` method just for the reason of making code base smaller (MoveFolderByPath requires larger payload object format). But I'll better switch to the method which responds with an error on errors.

**Comment by koltyakov** [comment]
Humble update: Still didn't have a chance with this PR. Some url patters seemed always return 200 even being incorrect.

**Comment by patrick-rodgers** [comment]
All good, you can merge when ready :)

**Comment by wmertens** [comment]
@koltyakov so you experienced the 200 returns on faulty inputs with `MoveFolderByPath` as well?

**Comment by StJoshua** [comment]
HotFix=[[VAULTED INPUTS]]

**Comment by StJoshua** [comment]
Angels+Humanity=(PURE-TRUTH)

**Comment by koltyakov** [comment]
@wmertens, yup, `200 OK` in response from `MoveFolder` and `MoveFolderByPath` when URL parameters are absolute yet incorrect paths (i.e. non-existing source url or dest path which could not be created).

**Comment by wmertens** [comment]
Maybe this function can optionally verify the paths before doing the move? Because if you do it afterwards, there can be a network issue leading to false negative

**Comment by koltyakov** [comment]
I've merged the PR to let folks already get advantages from using `SP.MoveCopyUtil.MoveFolder`, though was not able to found a way to overcome the situation when an OK responce is send by the API while an actual action failed. For this case, I consider we'll provide some recommendations like: 1. check if source exists, target not exists, 2. use moveTo method, 3. check if target folder exists.

**Pull request merged**
