### PR TITLE
Added subscriptions to Graph + documentation

### PR DESCRIPTION
**Pull request by simonagren**
#### Category
- [ ] Bug fix?
- [X] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### What's in this Pull Request?
The addition of Subscriotions functionality to the Graph Package.

- Get all
- Get By Id
- Create a New subscription
- Delete
- Update

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks, will have a look at merging this soon, appreciate your continued contributions!

**Comment by simonagren** [comment]
My pleasure Patrick 😀

**Comment by patrick-rodgers** [comment]
Thanks again @simonagren - always appreciate your help. Hope you're feeling better.

**Comment by simonagren** [comment]
@patrick-rodgers thank you for letting me be a part of this :) I'm feeling better, almost back in shape.

**Pull request merged**
