### PR TITLE
removing all graph support from PnPjs as required by the Graph Product Group

### PR DESCRIPTION
**Pull request by patrick-rodgers**
The Microsoft Graph Product Group has required that we remove all support for calling the Graph API from this library. This PR removes all support, docs, and references to the Microsoft Graph. The AdalClient package remains, though is now only of use to call the SharePoint APIs secured via AAD so will have limited use cases. This is a very unfortunate approach to open source taken by that team and one I disagree with strongly. I want to thank everyone that contributed to, used, and helped develop these capabilities - know that your work mattered and was appreciated. 🐇

### CODE REVIEW

**Comment by koltyakov** [comment]
Under any conclusions, it's the really strange and awkward signal from the Graph Product Group. 😵

**Comment by simonagren** [comment]
@patrick-rodgers @koltyakov this hurts :(

**Comment by gautamdsheth** [comment]
This is deeply disappointing decision. 

Questions:

1) What was the reason behind this request ? 

2) Why did we entertain this request ? What were the repercussions in rejecting the request ?

3) Since we already merged the PR , does this mean that Product Group has veto on the stuff that is built and maintained by the community ? I mean what stops the SharePoint product group from doing the same for PnP CSOM and PowerShell ?  Or the SPFx team from doing the same for the React controls repositories ?

**Comment by ypcode** [comment]
As already pointed on Twitter, it is really poor and unrespectful decision to all the awesome work done. Really dissapointed, and I hope this kind of moves won't happen again, because this overall awesome community will explode and I don't want to see that happening ! #SharingIsCaring

**Comment by jackpoz** [comment]
Maybe what this PR is missing is a link to existing alternatives, like https://github.com/microsoftgraph/msgraph-sdk-javascript , and what's left to do is to help users migrate to that library.

**Comment by joelfmrodrigues** [comment]
There must have been a valid reason for this option to be considered, but it definitely raises many concerns about how open source and community projects can be impacted by business decisions,
which in my opinion is not correct as we are talking about consuming an API...
Really hope that more information is provided and the change is discussed with the community (for example in a community call) so that we have the chance to ask questions.

**Comment by VelinGeorgiev** [comment]
People gave away their free time to contribute. This is not a joke. I strongly disagree.

**Comment by vman** [comment]
The communication about this to the community could have been a lot better. 

Other than this, it would be good to know if other PnP open source projects e.g. Office 365 CLI would also be losing Graph support?

**Comment by pdemro** [comment]
This move is a surprise and seems at-odds with Microsoft's embracing open source strategy the last few years.  It goes to show that the graph team is out-of-touch with the great work the PnP community has done over the years.  I would be surprised if their stance isn't reversed in the coming weeks.  Don't throw away the code @patrick-rodgers!

**Comment by tr5tn** [comment]
As mentioned on Twitter, this does call in to question if 1) Microsoft should be allowed to "own" OS projects if this can happen, and 2) whether @patrick-rodgers shouldn't be able to just reject it until there is public comment which either does or doesn't adequately justify the decision to the community.

**Comment by darrelmiller** [comment]
Hey folks, I'm the Microsoft Graph SDK PM.   I'm currently replying to this thread.   If you could hold off crucifying me until I get to reply, that would be much appreciated :-)

**Comment by jimmywim** [comment]
Just keep in mind the reason for these community projects. Microsoft's public APIs are very often convoluted to use in real-life scenarios. Look at Taxonomy. No REST API support, and I doubt we'll ever get it. So pnpjs gave us an easy to use pattern.

Whatever the replacement or reason for removing it is, there are tonnes of us in the field battling with flaky APIs every day and wrappers are created to make life easier. Case in point being ExecuteQueryRetry(Async) to handle 429s.

**Comment by SPDoctor** [comment]
This commit relates to v2,

**Comment by darrelmiller** [comment]
Hey folks.  I'm the PM who owns the Microsoft Graph SDKs, including the JavaScript SDK.  First let me apologize for the way this has been communicated to you.  I try very hard to provide our community with transparency into our plans and decision making process and in this case I didn't do a good job.

Community contributions are gold, and I cannot emphasize enough how much it would pain me to waste those contributions.  It is exactly for this reason, we the Graph SDK team are planning to provide a fluent JS API for the Graph SDKs.  It has been clear from the popularity of the PnPJS fluent effort and the Uservoice request for doing fluent in the Graph SDKs that this is an important feature for users.  The challenge of course is that Microsoft Graph is large and continually growing, and the beta API is even bigger.  Hand coding fluent APIs for all of this would take a massive amount of community effort.  The Graph SDK team doesn't have the resources to do that by hand, which is why we used the Graph metadata and generators to codegen the fluent API for other languages.  I would hate to see so much community effort being spent on doing something that is largely mechanical.

The intent to bring a fluent API into the JavaScript Graph SDK was communicated to Patrick earlier this year with same reasoning as I am presenting here.  It shouldn't be the community's job to provide basic functionality like this for the Microsoft Graph, especially considering the manual effort it would take for maintaining complete coverage.  We explained that we wanted to provide a clear message to our customers of where our efforts were being focused and what our documentation would reference and where support would be provided.  It seems our statement of intent was perhaps poorly phrased because Patrick has felt like he is been told that PnPJS should not make calls to the Graph.  And that sentiment had driven him to remove the Graph support from PnpJS.

It was not my intent to say PnPJS cannot call the the Graph, and I'd like to apologize to Patrick for that miscommunication.  What I do want to clearly communicate to all the awesome contributors to this project, is that your effort has proven that we need fluent support across all of the Microsoft Graph APIs, and I would love it if you let us take it from here and you take that time to build awesome apps for Microsoft Graph.  Now, I understand that maybe the fluent APIs we generate will not provide quite the same crafted experience that you currently have.  If you want to continue using those hand crafted fluent APIs, then more power to you.   I see no reason why the PnPJS Graph APIs cannot co-exist with the Graph SDK, as long as it is clear where our support and documentation efforts must be.  Community contributions to the PnPJS hand crafted fluent API have to be done with the full awareness that to some extent, our SDK team will be duplicating those efforts.

I will leave it in the capable hands of your community to decide if you want to continue investing time in something that you have demonstrated Microsoft needs to provide out of the box. But please do not underestimate how much we appreciate the effort of the developer community and please give us the opportunity to correct any perception you may have that we are not valuing your time.  I appreciate getting the opportunity to try and clarify the current situation and hopefully we can work more closely together in the future to avoid any further miscommunications.

**Comment by patrick-rodgers** [comment]
Want to follow up to @darrelmiller's comment and say that we are excited to have cleared up this misunderstanding. Sometimes messages in emails and chats get confused. Moving forward we will continue to include graph support in PnPjs v2 and it will exist alongside the official Graph SDK offerings across JS, PS, and other forms. I believe both projects represent different approaches to solving the same problem and at the end of the day we all win by having more choices to use, learn from, and share. Thank you @darrelmiller for reaching out this morning to clarify and talk through the confusion to arrive at a great resolution. Appreciate you clearly explaining things and look forward to working with you in the future.

**Comment by VesaJuvonen** [comment]
Thanks @patrick-rodgers  and @darrelmiller  for handling the confusion and we'll work internally at Microsoft to reduce similar public confusing messaging. This thread provided absolutely great visibility on the demand on the Fluid APIs for Graph and the direction where we are heading with both Graph SDKs and PnPjs. 

We are NOT looking to drop support for any of the existing open-source community projects which we currently are executing, so it's safe to invest time and effort on them. This thread and social media reactions is good reminder why we need to have more focus on external messaging to avoid any similar confusion in future.

Thanks everyone who have been involved in PnPjs and in our other community efforts. Community rocks! Sharing is caring! ❤

**Comment by SPDoctor** [comment]
@patrick-rodgers rejected his own pull request - Yay!

**Comment by jimmywim** [comment]
@darrelmiller Thanks for the detailed clarification. Good to hear things are moving on, sounds like everything's being `autorest`'d (or similar tech in place).

Excited to hear about Taxonomy management being done through Graph. I have a pending backlog item that's waiting for CSOM to go to dotnet core, but even if this is /beta of Graph then all the more awesome!

**Comment by darrelmiller** [comment]
@patrick-rodgers @VesaJuvonen   We are hiring a dev in the new year to work on the fluent API for JavasScript.  It would be great to get on a community call in January with the PnpJS folks most passionate about this feature to hear their requirements and make sure our code generation process builds the right thing across all of Microsoft Graph.  Can you help us make this happen?

**Comment by patrick-rodgers** [comment]
@darrelmiller - will do!

**Comment by VesaJuvonen** [comment]
@darrelmiller - as noted by @patrick-rodgers already, let's absolutely get a spot in January to talk about the requirements in the SharePoint Framework community calls, where we have a recurrent spot for the PnPjs topic. Let's agree details closer, but have preliminary blocked as spot at 30th of January, if that works. Let's confirm closer.

**Comment by phillipharding** [comment]
> @darrelmiller Thanks for the detailed clarification. Good to hear things are moving on, sounds like everything's being `autorest`'d (or similar tech in place).
> 
> Excited to hear about Taxonomy management being done through Graph. I have a pending backlog item that's waiting for CSOM to go to dotnet core, but even if this is /beta of Graph then all the more awesome!

@darrelmiller @jimmywim 
apart from your great clarification today, a dotnet core version of CSOM would be just about the most awesome thing you could do.....seriously 😃

**Comment by jimmywim** [comment]
> @darrelmiller @jimmywim
> apart from your great clarification today, a dotnet core version of CSOM would be just about the most awesome thing you could do.....seriously 😃

Tee'd up for Q1 2020:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/16585795-support-net-core-with-csom

**Comment by VesaJuvonen** [comment]
@phillipharding, @jimmywim  - as I noted in the UserVoice entry, we are actively working on the .NET Core version of the CSOM. Current ETA is for the first quarter of next year. This is not really for the Graph side of the house, as CSOM is native SharePoint specific API, but we do understand the demand for this. Getting it out has been delayed due numerous unfortunate issues, but we are hoping to finally get it out soon. 

Obviously there is already a .NET Core version of the Graph SDK, which can be used for the Graph APIs. Not really a topic of this PR or the discussion in here, but wanted to ensure that everyone is up to date on the plans.

As we can consider this PR discussion finalized, closing the PR from comments to avoid any of your input getting lost.

**Comment by simonagren** [comment]
Great to see things cleared up. Count me in @VesaJuvonen @darrelmiller @patrick-rodgers if there's any discussions regarding this <3

**Pull request merged**
