### PR TITLE
TokenHelper like implementation

### PR DESCRIPTION
**Pull request by pedro-pedrosa**
#### Category
- [ ] Bug fix?
- [x] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

Solves #338

#### What's in this Pull Request?

A token helper utility was added to the nodejs package to help with fetching addin-only tokens and user tokens.

A request context class was also added to abstract away token management from user code.

Usage:

```ts
import { Logger, LogLevel } from "@pnp/logging";
import { sp } from "@pnp/sp";
import { NodeFetchClient, getProviderHostedRequestContext } from "@pnp/nodejs";

declare var process: { exit(code?: number): void };

export async function test(settings: any) {

    // configure your node options
    sp.setup({
        sp: {
            fetchClientFactory: () => {
                return new NodeFetchClient();
            },
        },
    });

    try {
        const spAppToken = "{SPAppToken}";
        const ctx = await getProviderHostedRequestContext(settings.testing.sp.url, settings.testing.sp.id, settings.testing.sp.secret, spAppToken);
        const userSP = await ctx.getUserSP();
        const addinSP = await ctx.getAddinOnlySP();

        const user = await userSP.web.currentUser.get();
        Logger.log({
            data: user,
            level: LogLevel.Info,
            message: "User principal info",
        });

        const app = await addinSP.web.currentUser.get();
        Logger.log({
            data: app,
            level: LogLevel.Info,
            message: "App principal info",
        });

        process.exit(0);
    } catch (error) {
        Logger.error(error);
        process.exit(1);
    }
}
```

To get an SPAppToken, you can use this function in a browser:
```ts
async function fetchAppContextToken(webAbsoluteUrl, clientId, redirectUri) {
    const response = await fetch(`${webAbsoluteUrl}/_layouts/15/appredirect.aspx?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirectUri)}`);
    const parser = new DOMParser();
    const doc = parser.parseFromString(await response.text(), 'text/html');
    const form = doc.getElementById('frmRedirect');
    if (!form) {
        throw new Error('Invalid response from SharePoint');
    }
    const input = Array.from(form.getElementsByTagName('input')).find(i => i.name == 'SPAppToken');
    if (!input) {
        throw new Error('SPAppToken input form field not found');
    }
    return input.value;
}
```

Let me know how I should approach updating the docs. Also let me know if I should move these files to a different location.
I'm also thinking about updating the SPFetchClient to use the token helper methods since this is virtually a copy paste from there.

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Circling back to have a look at things today and currently these changes don't build (as shown in the Travis CI integration), which makes it hard to test. How were you able to test the changes?

For updating the docs you can add a page in the /docs folder under nodejs and update the mkdocs.yml file in the root to ensure the new page appears in the navigation as expected.

I agree there is a lot of code duplication so reducing that would be good - but we need to ensure we do not change existing behaviors for SPFetchClient.

One thing I just noticed as well is that you are referencing sp so the package.json would need to be updated to include those dependencies, and the tsconfig.json files would need their include paths updated. This is likely the source of the build errors. This change does force folks not using the sp libraries to install them to use the nodejs package. Not really a deal breaker, but something to be aware of - and would need to be added to the docs.

To merge this it would at a minimum need to build, and I would like to see the code cleaned up a bit to avoid having the duplication.

**Comment by pedro-pedrosa** [comment]
Not sure why the build is erroring. It works on my machine even after doing `git pull upstream dev`. I don't have any pending changes to commit or anything.

The errors don't reference any of the commited files either.

I was able to test this in VSCode using F5 which ran a modified version of the code I posted above.

```
> gulp build:test
[20:27:23] Using gulpfile D:\solutions\pnpjs\gulpfile.js
[20:27:23] Starting 'clean'...
[20:27:23]   Cleaning directories: ./dist, ./serve, ./site.
[20:27:23] Starting 'lint:tests'...
[20:27:28]   Cleaned directories: ./dist, ./serve, ./site.
[20:27:28] Finished 'clean' after 5.68 s
[20:27:33] Finished 'lint:tests' after 11 s
[20:27:33] Starting 'build:test'...
[20:27:37] Finished 'build:test' after 3.29 s
> gulp build:debug
[20:33:14] Using gulpfile D:\solutions\pnpjs\gulpfile.js
[20:33:14] Starting 'clean-build-debugging'...
[20:33:14] Starting 'bootstrap-buildsystem'...
[20:33:15] Finished 'clean-build-debugging' after 476 ms
[20:33:26] Finished 'bootstrap-buildsystem' after 12 s
[20:33:26] Starting 'build:debug'...
[20:33:26]   Beginning (0) pre-build tasks.
[20:33:26]   Finished pre-build tasks.
[20:33:26]   Processing build targets.
[20:33:43]   Processed build targets.
[20:33:43]   Beginning (1) post-build tasks.
[20:33:43]   Finished post-build tasks.
[20:33:43] Finished 'build:debug' after 17 s
```

**Comment by patrick-rodgers** [comment]
Code builds now, which is great. Please take a moment to add a docs page describing how to use this feature and we can look at getting things merged. Thanks.

**Comment by pedro-pedrosa** [comment]
Added documentation and removed token-specific code out of SPFetchClient.

Tested backwards-compatibility with SPFetchClient.

Let me know if this needs anything else.

**Comment by patrick-rodgers** [comment]
I did some code cleanup and changed slightly the usage, but I updated the docs page to reflect that change. Thanks for adding this.

**Pull request merged**
