### PR TITLE
Adding support for Webpack 4, cleanup 

### PR DESCRIPTION
**Pull request by patrick-rodgers**
#### Category
- [ ] Bug fix?
- [X] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

none

#### What's in this Pull Request?

- Adds support for webpack 4
- Project cleanup
- Enable webpack.config.js in root
- Clean up deps
- Optimize serve
- Various small changes and trimming where possible.

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
@koltyakov - if you get a chance please pull this down and do a quick sanity check that things work. You can debug, build, etc. This and the other PR of mine I already merged updated most of the tooling so want to make sure there aren't any "it works on my machine" moments. I also removed some stuff that is no longer used from package.json

**Comment by koltyakov** [comment]
@patrick-rodgers checking it now, btw. Will let you know shortly.

**Comment by patrick-rodgers** [comment]
On the upside all the build/debug tasks should run faster now :)

**Comment by koltyakov** [comment]
Build tasks work well on my (win) machine. Build time improvement is significant. Great job!
Can't check on macOS right now, but at least testing on another machine should reduce potential "it works on my machine" moments. 
Tests went well (with the exception of webhooks and taxonomy which I didn't configure properly here on the environment). Everything looks cool!

**Comment by patrick-rodgers** [comment]
Thanks! I wouldn't worry about testing on mac, the cli tests should catch any issues around filename casing etc. I will go ahead and merge this then and update changelog. Appreciate you taking a look.

**Pull request merged**
