### PR TITLE
Added getLockedByUser method on files

### LINKED ISSUE #2234: Missing lockedByUser method on Files
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [x] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question
Expected to use the lockedByUser method on files as per [https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj247073(v=office.15)](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj247073(v=office.15)) 

### Observed Behavior
lockedByUser method is missing

### Steps to Reproduce
NA

### PR DESCRIPTION
**Pull request by Taaqif**
#### Category
- [ ] Bug fix?
- [x] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues
fixes #2234

#### What's in this Pull Request?

Adds the missing locked by user method for files

### CODE REVIEW

**Comment by juliemturner** [comment]
@Taaqif  -- Thank you very much for your contribution, we'll have a look and get this in our 3.3 release

**Comment by Taaqif** [comment]
Awesome!
Hope to hear back soon on any updates

**Comment by patrick-rodgers** [comment]
I @Taaqif - this looks good. My only comment would be: did you consider importing and using "ISiteUserProps" from ../sites-users/types.ts instead of creating the new `ILockedByUser`? They look the same but perhaps there is a difference I missed. Regardless we'll get this merged in for 3.3.0. Thanks!!

**Comment by Taaqif** [comment]
@patrick-rodgers good point!
They are identical, I'll try and get that swapped out.

Thanks for the feedback 😊

**Comment by juliemturner** [comment]
@Taaqif  -- In preparation for our release tomorrow I went ahead and made the adjustment to your PR to use the ISiteUserProps, thank you very much for submitting this work, we always appreciate it.

**Pull request merged**
