### PR TITLE
Remove circular import

### LINKED ISSUE #2681: TypeError: Cannot read properties of undefined (reading 'prototype')
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 3.15.0

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
Updating from v3.14.0 to v3.15.0 should not break the build.

### Observed Behavior
Test are failing with `TypeError: Cannot read properties of undefined (reading 'prototype')`

```
FAIL libs/sp/common/src/lib/common.module.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'prototype')

    > 1 | import '@pnp/sp/sites';
        | ^
      2 | import '@pnp/sp/webs';
      3 | import '@pnp/sp/lists';
      4 | import '@pnp/sp/files';

      at Object.<anonymous> (../../node_modules/@pnp/sp/batching.js:13:6)
      at Object.<anonymous> (../../node_modules/@pnp/sp/behaviors/request-digest.js:6:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/index.js:13:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/webs/types.js:7:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/sites/types.js:4:1)
      at Object.<anonymous> (../../node_modules/@pnp/sp/sites/index.js:2:1)
      at Object.require (pnp/src/lib/pnp-imports.ts:1:1)
      at Object.require (pnp/src/lib/pnp.service.ts:1:1)
      at Object.require (pnp/src/public_api.ts:2:1)
      at Object.require (pnp/src/index.ts:2:1)
      at Object.require (common/src/lib/services/action/sp-permission.service.ts:21:1)
      at Object.require (common/src/lib/common.module.ts:4:1)
      at Object.<anonymous> (common/src/lib/common.module.spec.ts:2:1)
```

### Steps to Reproduce
I'm using a `nx` workspace with an angular library where i import the following pnpjs libs:

```ts
import '@pnp/sp/sites';
import '@pnp/sp/webs';
import '@pnp/sp/lists';
import '@pnp/sp/files';
import '@pnp/sp/folders';
import '@pnp/sp/fields/web';
import '@pnp/sp/fields/list';
import '@pnp/sp/items/list';
import '@pnp/sp/site-users/web';
import '@pnp/sp/profiles';
import '@pnp/sp/content-types/list';
import '@pnp/sp/content-types/web';
```
Testes are executed as `commonjs` from `typescript` with `jest` and `ts-jest` under the hood.

Let me know if further details are required

### PR DESCRIPTION
**Pull request by viceice**
#### Category
- [x] Bug fix?
- [ ] New feature?
- [ ] New sample?
- [ ] Documentation update?

#### Related Issues

- fixes #2681

#### What's in this Pull Request?

Remove a circular import from `@pnp/sp/webs/types` to itself.

### CODE REVIEW

**Comment by viceice** [comment]
i need some help, i now get the following error locally on windows:

```
*****************************
  1) "before all" hook: setup in "{root}"
Testing completed in 0.0060 seconds.
SP Teardown completed in 0.0000 seconds.
  2) "after all" hook: spTeardown in "{root}"

  0 passing (9ms)
  2 failing

  1) "before all" hook: setup in "{root}":
     Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'null' imported from ~\pnpjs\build\testing\test\load-settings.js
      at new NodeError (node:internal/errors:399:5)
      at packageResolve (node:internal/modules/esm/resolve:889:9)
      at moduleResolve (node:internal/modules/esm/resolve:938:20)
      at defaultResolve (node:internal/modules/esm/resolve:1153:11)
      at nextResolve (node:internal/modules/esm/loader:163:28)
      at file:///~/pnpjs/build/testing/tools/local-module-resolver/esm.js:46:62
      at nextResolve (node:internal/modules/esm/loader:163:28)
      at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
      at ESMLoader.import (node:internal/modules/esm/loader:525:22)
      at importModuleDynamically (node:internal/modules/esm/translators:110:35)
      at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
      at getSettings (file:///~/pnpjs/build/testing/test/load-settings.js:36:37)
      at Context.setup (file:///~/pnpjs/build/testing/test/mocha-root-hooks.js:23:36)
      at process.processImmediate (node:internal/timers:476:21)

  2) "after all" hook: spTeardown in "{root}":
     TypeError: Cannot read properties of undefined (reading 'args')
      at Context.spTeardown (file:///~/pnpjs/build/testing/test/mocha-root-hooks.js:100:30)
      at process.processImmediate (node:internal/timers:476:21)
```

**Comment by patrick-rodgers** [comment]
The challenge with this PR is you've updated a bunch of unrelated files for unclear reasons so we aren't able to just merge the actual fix for the circular ref. The description provided doesn't mention any of the other changes. Can you 1) expand the description to explain the other changes - or back them out and update the PR to just fix the circular ref? I can also just fix that circular ref issue and we can come back to this as you have time to expand on the reasoning.

**Comment by viceice** [comment]
the other changes are also because of circular references. but I've currently not enough time to go further, so feel free to pick the actual change to a separate PR. 🤗

we can then try to fix the other issues later, as they cause new issues because the loading of files changed, which causes new null reference errors.

**Comment by bcameron1231** [comment]
Thanks. I'll put this into it's own PR for now. We'll close this PR until you can find some time to update some of the information referenced by @patrick-rodgers . Thank you!

**Pull request closed without merging**
